/* AI WhatsApp parser v6
   Firebase-first address lookup, same provider as AI tab, robust API endpoint handling.
*/
(() => {
  'use strict';
  const state = { entries: [], addressBook: [], rawText: '' };
  const $ = id => document.getElementById(id);
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function toast(msg, type='error'){ if(window.showToast)window.showToast(msg,type); else alert(msg); }
  async function loadAddressBook(){
    try{const{fbDB,fbMethods,fbUser}=window;if(fbUser?.uid&&fbDB&&fbMethods?.getDoc){const snap=await fbMethods.getDoc(fbMethods.doc(fbDB,'users',fbUser.uid));const data=snap.data?snap.data():{};const raw=data?.customAddresses;const arr=Array.isArray(raw)?raw:(typeof raw==='string'?JSON.parse(raw||'[]'):[]);state.addressBook=Array.isArray(arr)?arr:[];localStorage.setItem('waCustomAddrs',JSON.stringify(state.addressBook));return state.addressBook;}}catch(e){console.warn('[AI parser] Firebase address lookup failed:',e)}
    try{const arr=JSON.parse(localStorage.getItem('waCustomAddrs')||'[]');state.addressBook=Array.isArray(arr)?arr:[];return state.addressBook}catch{state.addressBook=[];return[]}
  }
  async function learnAddress(addr,type,price=0){
    addr=String(addr||'').trim();if(!addr||type==='unknown')return;const list=await loadAddressBook(),i=list.findIndex(x=>String(x.addr||'').toLowerCase()===addr.toLowerCase());const entry={addr,type,price:Number(price)||0};if(i>=0)list[i]=entry;else list.push(entry);state.addressBook=list;localStorage.setItem('waCustomAddrs',JSON.stringify(list));
    try{const{fbDB,fbMethods,fbUser}=window;if(fbUser?.uid&&fbDB&&fbMethods?.setDoc)await fbMethods.setDoc(fbMethods.doc(fbDB,'users',fbUser.uid),{customAddresses:JSON.stringify(list),customAddressesUpdated:Date.now()},{merge:true})}catch(e){console.warn('[AI parser] learning failed:',e)}
  }
  function normalize(s){return String(s||'').toLowerCase().replace(/ё/g,'е').replace(/[.,;:!?()\[\]{}]/g,' ').replace(/\s+/g,' ').trim()}
  function addrMatch(input,item){const a=normalize(input),b=normalize(item?.addr);return!!a&&!!b&&(a===b||a.includes(b)||b.includes(a))}
  function specialRule(address){const a=normalize(address);if(a.includes('валерьяновка')||a.includes('октябрьский'))return{type:'other',amount:2500};if(a.includes('дач')&&(a.includes('кпп')||a.includes('контрольно пропуск')))return{type:'other',amount:2000};if(a.includes('дач')&&(a.includes('домик')||a.includes('до дома')))return{type:'other',amount:2800};if(a.includes('речк'))return{type:'other',amount:1500};if(a.includes('домик газовика')||a.includes('газовик'))return{type:'other',amount:1000};if(a.includes('гараж')||a.includes('коттедж')||a.includes('колизей'))return{type:'under',amount:150};return null}
  function defaultAmount(point,type){return type==='flat'?(String(point).toUpperCase().includes('ALLEY')?900:300):(String(point).toUpperCase().includes('ALLEY')?600:150)}
  function extractJson(text){let s=String(text||'').trim().replace(/^```json\s*/i,'').replace(/^```\s*/,'').replace(/\s*```$/,'').trim();const f=s.indexOf('{'),l=s.lastIndexOf('}');if(f>=0&&l>=f)s=s.slice(f,l+1);const p=JSON.parse(s);return Array.isArray(p)?p:(p.orders||p.items||[])}
  async function fetchWithTimeout(url,options,ms=45000){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),ms);try{return await fetch(url,{...options,signal:ctrl.signal,cache:'no-store'})}catch(e){if(e.name==='AbortError')throw new Error('Тайм-аут AI (45 секунд). Проверь интернет и доступность выбранного провайдера.');throw new Error('Не удалось подключиться к AI API. Проверь интернет, API-ключ и выбранного провайдера. Технически: '+e.message)}finally{clearTimeout(timer)}}
  async function getProvider(){const p=localStorage.getItem('aiProvider')||'gemini',map={gemini:'geminiKey',openai:'openaiKey',claude:'claudeKey',qwen:'qwenKey',groq:'groqKey',custom:'customKey'},key=await window._SEC.getApiKey(map[p]||'geminiKey');if(!key)throw new Error(`Нет API-ключа для ${p}. Открой вкладку «ИИ» и настрой выбранного провайдера.`);return{p,key}}
  function buildPrompt(book){const bt=book.length?book.map(x=>`- ${x.addr} => ${x.type==='flat'?'КВАРТИРА':x.type==='under'?'ПОДЪЕЗД':'ДРУГОЕ'}${x.price?`, цена ${x.price}`:''}`).join('\n'):'(справочник пуст)';return `Ты разбираешь сообщения курьерской службы из WhatsApp. Не угадывай молча.\n\nСНАЧАЛА используй справочник адресов ниже. Если адрес совпадает или явно является вариантом записи из справочника, его тип и цена имеют приоритет над общими правилами.\n\nСПРАВОЧНИК FIREBASE:\n${bt}\n\nОбщие знания:\n- F1/F2/F3: до подъезда обычно 150, до квартиры обычно 300.\n- ALLEY PUB: до подъезда 600, до квартиры 900.\n- Гаражи, коттеджи и Колизей считаются как до подъезда.\n- Валерьяновка и Октябрьский: 2500.\n- Дачи до домика: 2800.\n- Дачи до КПП: 2000.\n- Речка: 1500.\n- Домик газовика: 1000.\n- Сокращения КВ, П, ПОД не обязательны. Понимай смысл и структуру адреса. Например «1-24-4п» может означать подъезд, а «4-1-105 (домофон 175)» — квартиру.\n\nВерни строго JSON: {"orders":[{"point":"F1","address":"...","type":"flat|under|other|unknown","amount":300,"msgTime":"20:04","confidence":0.0,"question":""}]}\nЕсли не уверен, type=unknown, confidence ниже 0.75 и напиши короткий question. Не придумывай отсутствующий адрес или телефон. Телефоны убирай из address.\n\nТекст WhatsApp:\n`}
  async function askAI(text,book){const{p,key}=await getProvider(),prompt=buildPrompt(book);if(p==='gemini'){const model=localStorage.getItem('geminiModel')||'gemini-2.5-flash',url=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`,res=await fetchWithTimeout(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({system_instruction:{parts:[{text:prompt}]},contents:[{role:'user',parts:[{text}]}],generationConfig:{responseMimeType:'application/json',temperature:.1}})}),raw=await res.text();if(!res.ok)throw new Error(`Gemini HTTP ${res.status}: ${raw.slice(0,500)}`);let data;try{data=JSON.parse(raw)}catch{throw new Error('Gemini вернул не JSON: '+raw.slice(0,200))}if(data.error)throw new Error(data.error.message||JSON.stringify(data.error));const out=data.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||'';if(!out)throw new Error('Gemini не вернул текст ответа.');return extractJson(out)}
    let base,model;if(p==='openai'){base='https://api.openai.com/v1';model=localStorage.getItem('openaiModel')||'gpt-4o-mini'}else if(p==='groq'){base='https://api.groq.com/openai/v1';model=localStorage.getItem('groqModel')||'llama-3.3-70b-versatile'}else if(p==='qwen'){base='https://dashscope.aliyuncs.com/compatible-mode/v1';model=localStorage.getItem('qwenModel')||'qwen-turbo'}else if(p==='custom'){base=(localStorage.getItem('customUrl')||'').trim().replace(/\/+$/,'');model=localStorage.getItem('customModel')||'gpt-4o-mini';if(!base)throw new Error('Для Custom не указан Base URL.');base=base.replace(/\/chat\/completions$/i,'');if(!/\/v1$/i.test(base))base+='/v1'}else if(p==='claude'){const model=localStorage.getItem('claudeModel')||'claude-haiku-4-5',res=await fetchWithTimeout('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':key,'anthropic-version':'2023-06-01','anthropic-dangerous-direct-browser-access':'true'},body:JSON.stringify({model,max_tokens:2048,system:prompt,messages:[{role:'user',content:text}]})}),raw=await res.text();if(!res.ok)throw new Error(`Claude HTTP ${res.status}: ${raw.slice(0,500)}`);const data=JSON.parse(raw);if(data.error)throw new Error(data.error.message||JSON.stringify(data.error));return extractJson(data.content?.find(x=>x.type==='text')?.text||'')}
    const url=base+'/chat/completions',res=await fetchWithTimeout(url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+key},body:JSON.stringify({model,temperature:.1,response_format:{type:'json_object'},messages:[{role:'system',content:prompt},{role:'user',content:text}]})}),raw=await res.text();if(!res.ok){if(raw.trim().startsWith('<'))throw new Error(`${p}: сервер вернул HTML вместо JSON.\nЗапрос: ${url}\nПроверь Base URL в настройках ИИ.`);throw new Error(`${p} HTTP ${res.status}: ${raw.slice(0,500)}`)}if(raw.trim().startsWith('<'))throw new Error(`${p}: сервер вернул HTML вместо JSON.\nЗапрос: ${url}\nПроверь Base URL в настройках ИИ.`);let data;try{data=JSON.parse(raw)}catch{throw new Error(`${p}: сервер вернул не JSON: ${raw.slice(0,250)}`)}if(data.error)throw new Error(data.error.message||JSON.stringify(data.error));return extractJson(data.choices?.[0]?.message?.content||'')}
  function resolveOrders(orders,book){return orders.map((o,i)=>{const point=String(o.point||'').toUpperCase(),address=String(o.address||'').trim(),found=book.find(x=>addrMatch(address,x)),special=specialRule(address);let type=found?.type||special?.type||String(o.type||'unknown').toLowerCase(),amount=found?.price>0?Number(found.price):(special?.amount||0);if(!['under','flat','other'].includes(type))type='unknown';if(!amount&&type!=='unknown')amount=defaultAmount(point,type);const c=Number(o.confidence),uncertain=type==='unknown'||(Number.isFinite(c)&&c<.75);return{id:i,point:o.point||'F1',address,type,amount,msgTime:String(o.msgTime||''),confidence:Number.isFinite(c)?c:0,question:o.question||`Как записать «${address||'этот адрес'}»?`,uncertain,foundInBook:!!found}})}
  function render(){const result=$('waResult'),list=$('waList');if(!result||!list)return;const unresolved=state.entries.filter(e=>e.uncertain);if(!state.entries.length){list.innerHTML='<div class="muted">Ничего не найдено.</div>';result.style.display='block';return}list.innerHTML=state.entries.map((e,i)=>{const label=e.type==='flat'?'до квартиры':e.type==='under'?'до подъезда':e.type==='other'?'другое':'нужно уточнение',q=e.uncertain?`<div style="margin-top:8px;background:#2a2210;border:1px solid #5c4b1a;border-radius:10px;padding:10px;color:#ffd166;">❓ ${esc(e.question)}<div style="margin-top:8px;display:flex;gap:6px;flex-wrap:wrap;"><button onclick="window.aiWAChoice(${i},'under')" style="padding:8px 10px;border:0;border-radius:8px;background:#4a9eff;color:#fff;font-weight:600;">До подъезда</button><button onclick="window.aiWAChoice(${i},'flat')" style="padding:8px 10px;border:0;border-radius:8px;background:#65d48b;color:#000;font-weight:600;">До квартиры</button><button onclick="window.aiWAChoice(${i},'other')" style="padding:8px 10px;border:0;border-radius:8px;background:#ffd166;color:#000;font-weight:600;">Другое</button></div></div>`:'';return `<div style="padding:10px 0;border-bottom:1px solid #1a1a1a;"><div style="display:flex;justify-content:space-between;gap:8px;"><div><div style="font-size:14px;font-weight:600;">${esc(e.point)} · ${esc(label)}</div><div style="font-size:13px;color:#c0c0c0;margin-top:3px;">${esc(e.address)}</div>${e.msgTime?`<div style="font-size:11px;color:#888;margin-top:2px;">🕐 ${esc(e.msgTime)}</div>`:''}${e.foundInBook?'<div style="font-size:10px;color:#65d48b;margin-top:3px;">✓ из Firebase</div>':''}</div><div style="text-align:right;white-space:nowrap;"><span style="color:#65d48b;font-weight:bold;">${e.uncertain?'—':Number(e.amount).toLocaleString()+' ₸'}</span><button onclick="window.aiWARemove(${i})" style="display:block;margin-left:auto;background:none;border:none;color:#ff6b6b;font-size:18px;padding:4px;">✕</button></div></div>${q}</div>`}).join('')+`<div style="display:flex;justify-content:space-between;padding:12px 0;font-weight:bold;"><span>Итого (${state.entries.filter(e=>!e.uncertain).length}/${state.entries.length})</span><span style="color:#65d48b;">${state.entries.filter(e=>!e.uncertain).reduce((s,e)=>s+Number(e.amount||0),0).toLocaleString()} ₸</span></div>`;result.style.display='block';const save=$('saveWABtn');if(save){save.disabled=unresolved.length>0||!state.entries.length;save.textContent=unresolved.length?`❓ Уточни ${unresolved.length} запис.`:'✅ Записать всё'}}
  window.aiWAChoice=async(i,type)=>{const e=state.entries[i];if(!e)return;e.type=type;e.uncertain=false;e.amount=defaultAmount(e.point,type);if(type==='other'){const v=prompt('Укажи сумму для этой записи:','');const n=Number(v);if(!n){e.uncertain=true;render();return}e.amount=n}await learnAddress(e.address,type,e.amount);e.foundInBook=true;render()};window.aiWARemove=i=>{state.entries.splice(i,1);render()};
  window.parseWA=async()=>{const input=$('waInput'),text=input?.value.trim();if(!text)return toast('Вставь текст из WhatsApp','error');const btn=document.querySelector('#tab-wa .card button');if(btn){btn.disabled=true;btn.textContent='⏳ Firebase → AI анализирует...'}try{const book=await loadAddressBook(),orders=await askAI(text,book);state.rawText=text;state.entries=resolveOrders(orders,book);render()}catch(e){console.error('[AI parser]',e);toast('Ошибка умного разбора: '+e.message,'error')}if(btn){btn.disabled=false;btn.textContent='🤖 Разобрать'}};
  window.saveWA=async()=>{if(!state.entries.length)return;const unresolved=state.entries.filter(e=>e.uncertain);if(unresolved.length)return toast('Сначала ответь на вопросы по неоднозначным адресам.','error');const btn=$('saveWABtn');if(btn){btn.disabled=true;btn.textContent='⏳ Записываю...'}try{const{fbDB,fbMethods,fbUser}=window;if(!fbUser?.uid)throw new Error('Нет авторизации Firebase.');const txRef=fbMethods.collection(fbDB,'users',fbUser.uid,'transactions'),now=new Date();if(now.getHours()<3)now.setDate(now.getDate()-1);const today=new Date(now-now.getTimezoneOffset()*60000).toISOString().split('T')[0],time=new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'}),existing=(window.allTx||[]).filter(t=>t.date===today&&t.type==='income'&&t.categoryName==='Доставка'),keys=new Set(existing.map(t=>`${t.subcategory}|${String(t.comment||'').trim().toLowerCase()}|${t.waTime||''}`));let saved=0,skipped=0;for(const e of state.entries){const key=`${e.point}|${e.address.trim().toLowerCase()}|${e.msgTime||''}`;if(keys.has(key)){skipped++;continue}await fbMethods.addDoc(txRef,{type:'income',amount:Number(e.amount),categoryName:'Доставка',subcategory:e.point,account:'Наличные',date:today,time,comment:e.address,waTime:e.msgTime||'',createdAt:Date.now()});keys.add(key);saved++}state.entries=[];const input=$('waInput');if(input)input.value='';if($('waResult'))$('waResult').style.display='none';toast(`✅ Записано: ${saved}${skipped?` | Дублей: ${skipped}`:''}`);if(window.render)window.render()}catch(e){toast('Ошибка записи: '+e.message,'error')}if(btn){btn.disabled=false;btn.textContent='✅ Записать всё'}};
  function install(){window._aiWhatsAppParserV6=true;const btn=$('saveWABtn');if(btn)btn.onclick=window.saveWA}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();